export const contactInfo = [
  {
    name: "Github",
    description: "https://github.com/CarlosHenriqueWebdev",
    url: "https://github.com/CarlosHenriqueWebdev",
    imageSrc: "/github-blue.svg",
    whiteImageSrc: "/white-icons/github-white.svg",
    display: true,
    isForContact: false,
  },
  {
    name: "Linkedin",
    description: "https://linkedin.com/",
    url: "https://linkedin.com/",
    imageSrc: "/linkedin-amethyst.svg",
    whiteImageSrc: "/white-icons/linkedin-white.svg",
    display: true,
    isForContact: false,
  },
  {
    name: "carloshenrique.webdev@gmail.com",
    url: "mailto:carloshenrique.webdev@gmail.com",
    imageSrc: "/email-blue.svg",
    whiteImageSrc: "/white-icons/email-white.svg",
    display: true,
    isForContact: true,
  },
  {
    name: "+993594837261",
    url: "https://wa.me/+993594837261",
    imageSrc: "/whatsapp-amethyst.svg",
    whiteImageSrc: "/white-icons/whatsapp-white.svg",
    display: true,
    isForContact: true,
  },
  {
    name: "http://localhost:3000/resume",
    url: "XXX",
    imageSrc: "/website-icon.svg",
    whiteImageSrc: "/white-icons/website-white.svg",
    display: false,
    isForContact: false,
  },
  {
    name: "Minas Gerais, Itájuba",
    url: "https://www.google.com/maps/place/Itajub%C3%A1,+MG/@-22.4329106,-45.4590676,14z/data=!3m1!4b1!4m6!3m5!1s0x94cb638240ee9d05:0x9c782630346ca79d!8m2!3d-22.4247429!4d-45.4601323!16s%2Fg%2F11bxfwt6wr?entry=ttu",
    addressLine1: "XXX",
    addressLine2: "XXX",
    whiteImageSrc: "/white-icons/address-white.svg",
    display: false,
    isForContact: true,
  },
];
