export const contactInfo = [
  {
    name: "CarlosHenriqueWebdev",
    description: "Github",
    url: "https://github.com/CarlosHenriqueWebdev",
    imageSrc: "/assets/github-blue.svg",
    whiteImageSrc: "/assets/white-icons/github-white.svg",
    display: true,
    isForContact: false,
  },
  {
    name: "LinkedIn",
    description: "LinkedIn",
    url: "https://www.linkedin.com/in/carlos-henrique-do-carmo-2761842b0/",
    imageSrc: "/assets/linkedin-amethyst.svg",
    whiteImageSrc: "/assets/white-icons/linkedin-white.svg",
    display: true,
    isForContact: false,
  },
  {
    name: "carloshenrique.webdev@gmail.com",
    url: "mailto:carloshenrique.webdev@gmail.com",
    imageSrc: "/assets/email-blue.svg",
    whiteImageSrc: "/assets/white-icons/email-white.svg",
    display: true,
    isForContact: true,
  },
  {
    name: "+5535998589234",
    url: "https://wa.me/+5535998589234",
    imageSrc: "/assets/whatsapp-amethyst.svg",
    whiteImageSrc: "/assets/white-icons/whatsapp-white.svg",
    display: true,
    isForContact: true,
  },
  {
    name: "carloshenriquedev.com",
    url: "https://www.carloshenriquedev.com/en",
    imageSrc: "/assets/website-icon.svg",
    whiteImageSrc: "/assets/white-icons/website-white.svg",
    display: false,
    isForContact: false,
  },
  {
    name: "Minas Gerais, Itájuba",
    url: "https://www.google.com/maps/place/Itajub%C3%A1,+MG/@-22.4329106,-45.4590676,14z/data=!3m1!4b1!4m6!3m5!1s0x94cb638240ee9d05:0x9c782630346ca79d!8m2!3d-22.4247429!4d-45.4601323!16s%2Fg%2F11bxfwt6wr?entry=ttu",
    whiteImageSrc: "/assets/white-icons/address-white.svg",
    display: false,
    isForContact: true,
  },
];
